# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4298695548d156f08f984ad6499a7d3799df19508ce99af12d0deb8e3439d70ab39c13602f8aecb2248cca105b244d763e195083110818939881fe2396d9bed5

test:
  secret_key_base: 3ca704526e6315d7c4c85a44a094b34596f35e91da96af71b71e6928b0d780105914736c37e0882b2e0585c2cba7f4331b0f0a696f9e79c015069108b298bee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
